#!/usr/bin/env python
"""Generate the landmark replay fixtures used by demo fallback A.

Why these exist
---------------
`docs/hackathon-demo-plan.md` §3 Fallback A: when the venue camera fails, the demo still has
to show the *pipeline* working — landmarks in, decision layer, editable text out. The app can
replay recorded landmark sequences through exactly the same code path the camera feeds
(`lib/vision/use-sign-recognition.ts`), so nothing about the demo is faked or bypassed.

What they are NOT
-----------------
They are **not recordings of anyone signing**, and they are not ISL. They are generated by
`ml/signdata/synthetic.py`, the same generator the pipeline smoke test uses. Every file
carries `notForRealUse: true` and a `notice` saying so, and the app displays the smoke-test
banner when a model built from this data is loaded.

Run with:
    npm run ml:fixtures

Writes:
    public/fixtures/replay-manifest.json
    public/fixtures/<class>.json
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "ml"))

from signdata.io import write_json  # noqa: E402
from signdata.synthetic import SyntheticConfig, generate_frames  # noqa: E402

OUTPUT_DIR = REPO_ROOT / "public" / "fixtures"

#: Kept small: the manifest is committed, and the app only needs enough frames to show a
#: sign being held and then released.
FRAMES_PER_FIXTURE = 90

NOTICE = (
    "Procedurally generated hand and pose landmarks. These are NOT recordings of anyone "
    "signing and have no relationship to Indian Sign Language. They exist only so the "
    "recognition pipeline can be demonstrated and tested without a camera. Never present "
    "these as sign recognition."
)


def main() -> int:
    config = SyntheticConfig(
        signer_count=1,
        positive_classes=6,
        reps_per_signer=1,
        frames_per_rep=FRAMES_PER_FIXTURE,
        label="replay",
        seed=90210,
    )

    windows = generate_frames(config)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # `generate_frames` guarantees at least two signers so the training pipeline always has
    # someone to hold out. The replay demo only needs one performer per sign, so take the
    # first window for each label — otherwise two signers would write the same filename and
    # the manifest would list the same file twice.
    first_per_label: dict[str, list[dict[str, object]]] = {}
    for key, frames in windows.items():
        _signer, label = key.split("|", 1)
        first_per_label.setdefault(label, frames)  # type: ignore[arg-type]

    manifest: list[dict[str, object]] = []
    written: list[str] = []

    for label, frames in first_per_label.items():
        # `timestampMs` is dropped: the hook assigns its own monotonic timestamps so the
        # landmarker's timestamp guard behaves the same as it does with a live camera.
        payload_frames = [
            {"hands": frame["hands"], "pose": frame["pose"]} for frame in frames[:FRAMES_PER_FIXTURE]
        ]
        file_name = f"{label.lower()}.json"
        write_json(
            OUTPUT_DIR / file_name,
            {
                "label": label,
                "source": "synthetic-generator",
                "notForRealUse": True,
                "notice": NOTICE,
                "frameCount": len(payload_frames),
                "frames": payload_frames,
            },
        )
        manifest.append(
            {
                "file": file_name,
                "label": label,
                "notForRealUse": True,
                "frameCount": len(payload_frames),
            }
        )
        written.append(file_name)

    # The `OTHER` fixture is deliberately included: it is the one that exercises rejection,
    # and a demo that only ever shows successful recognition is not a demo of this product.
    write_json(
        OUTPUT_DIR / "replay-manifest.json",
        {
            "schemaVersion": 1,
            "generator": "ml/scripts/build_replay_fixtures.py",
            "source": "synthetic-generator",
            "notForRealUse": True,
            "notice": NOTICE,
            "fixtures": manifest,
        },
    )

    print(f"[build_replay_fixtures] Wrote {len(written)} fixture(s) and a manifest to {OUTPUT_DIR.relative_to(REPO_ROOT)}")
    print(f"[build_replay_fixtures] Labels: {', '.join(entry['label'] for entry in manifest)}")
    print("[build_replay_fixtures] These are generated landmarks, not sign recordings.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
