/**
 * Feature extraction and normalisation — the TypeScript half of the parity pair.
 *
 * The Python implementation lives in `ml/signdata/features.py`. The two MUST produce
 * identical vectors; `tests/features-parity.test.ts` checks that against fixtures
 * generated by `ml/scripts/build_fixtures.py` (risk R14 in `docs/risk-register.md`).
 *
 * Layout is documented on `FEATURE_VECTOR_LENGTH` in `lib/types.ts`. Any change here
 * requires: bump FEATURE_VERSION, regenerate fixtures, retrain, update the model card.
 */

import {
  FEATURE_VECTOR_LENGTH,
  type FrameLandmarks,
  type HandLandmarks,
  type Landmark,
  type PoseLandmarks,
} from '@/lib/types';

export const HAND_LANDMARK_COUNT = 21;

/** MediaPipe Hand Landmarker indices. */
export const HAND = {
  WRIST: 0,
  THUMB_CMC: 1,
  THUMB_MCP: 2,
  THUMB_IP: 3,
  THUMB_TIP: 4,
  INDEX_MCP: 5,
  INDEX_PIP: 6,
  INDEX_DIP: 7,
  INDEX_TIP: 8,
  MIDDLE_MCP: 9,
  MIDDLE_PIP: 10,
  MIDDLE_DIP: 11,
  MIDDLE_TIP: 12,
  RING_MCP: 13,
  RING_PIP: 14,
  RING_DIP: 15,
  RING_TIP: 16,
  PINKY_MCP: 17,
  PINKY_PIP: 18,
  PINKY_DIP: 19,
  PINKY_TIP: 20,
} as const;

/** MediaPipe Pose Landmarker indices used for sign location. */
export const POSE = {
  NOSE: 0,
  LEFT_SHOULDER: 11,
  RIGHT_SHOULDER: 12,
  LEFT_HIP: 23,
  RIGHT_HIP: 24,
  POSE_LANDMARK_COUNT: 33,
} as const;

/** Joint triples `[a, b, c]`; the extension angle is measured at `b`. */
const EXTENSION_JOINTS: ReadonlyArray<readonly [number, number, number]> = [
  [HAND.THUMB_CMC, HAND.THUMB_MCP, HAND.THUMB_TIP],
  [HAND.INDEX_MCP, HAND.INDEX_PIP, HAND.INDEX_TIP],
  [HAND.MIDDLE_MCP, HAND.MIDDLE_PIP, HAND.MIDDLE_TIP],
  [HAND.RING_MCP, HAND.RING_PIP, HAND.RING_TIP],
  [HAND.PINKY_MCP, HAND.PINKY_PIP, HAND.PINKY_TIP],
];

/** Fingertips in the same order as `EXTENSION_JOINTS`. */
const FINGERTIPS: readonly number[] = [
  HAND.THUMB_TIP,
  HAND.INDEX_TIP,
  HAND.MIDDLE_TIP,
  HAND.RING_TIP,
  HAND.PINKY_TIP,
];

/** Guards against division by zero for degenerate hands; identical in Python. */
const EPSILON = 1e-6;

type Vec3 = readonly [number, number, number];

function sub(a: Vec3, b: Vec3): Vec3 {
  return [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
}

function norm(v: Vec3): number {
  return Math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
}

function dot(a: Vec3, b: Vec3): number {
  return a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
}

function cross(a: Vec3, b: Vec3): Vec3 {
  return [
    a[1] * b[2] - a[2] * b[1],
    a[2] * b[0] - a[0] * b[2],
    a[0] * b[1] - a[1] * b[0],
  ];
}

/** Angle between two vectors in radians, clamped to [0, PI]. Degenerate input -> 0. */
function angleBetween(a: Vec3, b: Vec3): number {
  const na = norm(a);
  const nb = norm(b);
  if (na < EPSILON || nb < EPSILON) return 0;
  const cosine = Math.min(1, Math.max(-1, dot(a, b) / (na * nb)));
  return Math.acos(cosine);
}

function toVec3(landmark: Landmark | undefined): Vec3 {
  if (!landmark) return [0, 0, 0];
  const { x, y, z } = landmark;
  return [Number.isFinite(x) ? x : 0, Number.isFinite(y) ? y : 0, Number.isFinite(z) ? z : 0];
}

function isUsable(landmark: Landmark | undefined): boolean {
  return (
    !!landmark &&
    Number.isFinite(landmark.x) &&
    Number.isFinite(landmark.y) &&
    Number.isFinite(landmark.z)
  );
}

/* ------------------------------------------------------------------------------------
 * Per-hand primitives
 * ---------------------------------------------------------------------------------- */

/**
 * Translate so the wrist is the origin, then scale by the wrist -> middle-finger-MCP
 * distance so the result is invariant to hand size and camera distance.
 *
 * Rotation normalisation is deliberately NOT applied: palm orientation is a
 * distinguishing parameter of ISL signs (`docs/technical-research.md` §1.3), so
 * removing it would destroy signal. `docs/ai-ml-and-dataset-plan.md` §4 leaves this
 * as an experiment; the result is recorded in `docs/implementation-decisions.md` (D-08).
 */
export function normaliseHand(landmarks: Landmark[]): Float32Array {
  const out = new Float32Array(HAND_LANDMARK_COUNT * 3);
  if (landmarks.length < HAND_LANDMARK_COUNT) return out;

  const wrist = toVec3(landmarks[HAND.WRIST]);
  const middleMcp = toVec3(landmarks[HAND.MIDDLE_MCP]);
  const rawScale = norm(sub(middleMcp, wrist));
  const scale = rawScale < EPSILON ? 1 : rawScale;

  for (let i = 0; i < HAND_LANDMARK_COUNT; i += 1) {
    const p = toVec3(landmarks[i]);
    out[i * 3] = (p[0] - wrist[0]) / scale;
    out[i * 3 + 1] = (p[1] - wrist[1]) / scale;
    out[i * 3 + 2] = (p[2] - wrist[2]) / scale;
  }
  return out;
}

/** Unit normal of the palm plane, from the wrist/index-MCP/pinky-MCP triple. */
export function palmNormal(landmarks: Landmark[]): Vec3 {
  if (landmarks.length < HAND_LANDMARK_COUNT) return [0, 0, 0];
  const wrist = toVec3(landmarks[HAND.WRIST]);
  const indexMcp = toVec3(landmarks[HAND.INDEX_MCP]);
  const pinkyMcp = toVec3(landmarks[HAND.PINKY_MCP]);
  const normal = cross(sub(indexMcp, wrist), sub(pinkyMcp, wrist));
  const length = norm(normal);
  if (length < EPSILON) return [0, 0, 0];
  return [normal[0] / length, normal[1] / length, normal[2] / length];
}

/** Wrist -> fingertip distances in *normalised* (hand-size) units. */
export function fingertipDistances(landmarks: Landmark[]): number[] {
  const out = [0, 0, 0, 0, 0];
  if (landmarks.length < HAND_LANDMARK_COUNT) return out;
  const wrist = toVec3(landmarks[HAND.WRIST]);
  const middleMcp = toVec3(landmarks[HAND.MIDDLE_MCP]);
  const rawScale = norm(sub(middleMcp, wrist));
  const scale = rawScale < EPSILON ? 1 : rawScale;

  for (let i = 0; i < FINGERTIPS.length; i += 1) {
    const tipIndex = FINGERTIPS[i] as number;
    const tip = toVec3(landmarks[tipIndex]);
    out[i] = norm(sub(tip, wrist)) / scale;
  }
  return out;
}

/**
 * Extension angle (radians) at the middle joint of each finger.
 * A fully extended finger approaches PI; a fully curled finger approaches 0.
 */
export function extensionAngles(landmarks: Landmark[]): number[] {
  const out = [0, 0, 0, 0, 0];
  if (landmarks.length < HAND_LANDMARK_COUNT) return out;
  for (let i = 0; i < EXTENSION_JOINTS.length; i += 1) {
    const joint = EXTENSION_JOINTS[i] as readonly [number, number, number];
    const a = toVec3(landmarks[joint[0]]);
    const b = toVec3(landmarks[joint[1]]);
    const c = toVec3(landmarks[joint[2]]);
    out[i] = angleBetween(sub(a, b), sub(c, b));
  }
  return out;
}

/** Mean of the hand's landmark coordinates in original image space. */
export function handCentroid(landmarks: Landmark[]): { x: number; y: number } {
  if (landmarks.length === 0) return { x: 0, y: 0 };
  let sx = 0;
  let sy = 0;
  let n = 0;
  for (const landmark of landmarks) {
    if (!isUsable(landmark)) continue;
    sx += landmark.x;
    sy += landmark.y;
    n += 1;
  }
  if (n === 0) return { x: 0, y: 0 };
  return { x: sx / n, y: sy / n };
}

/* ------------------------------------------------------------------------------------
 * Hand selection
 * ---------------------------------------------------------------------------------- */

/**
 * Collapse an arbitrary list of detected hands into the fixed `[left, right]` slot
 * order. When MediaPipe reports two hands of the same handedness (rare, but it happens
 * with occlusion), the higher-scoring one wins.
 */
export function selectHandSlots(hands: HandLandmarks[]): [HandLandmarks | null, HandLandmarks | null] {
  let left: HandLandmarks | null = null;
  let right: HandLandmarks | null = null;

  for (const hand of hands) {
    if (hand.landmarks.length < HAND_LANDMARK_COUNT) continue;
    if (hand.handedness === 'Left') {
      if (!left || hand.score > left.score) left = hand;
    } else if (!right || hand.score > right.score) {
      right = hand;
    }
  }

  return [left, right];
}

/* ------------------------------------------------------------------------------------
 * Full frame -> feature vector
 * ---------------------------------------------------------------------------------- */

export interface HandFeatureDebug {
  slot: 'left' | 'right';
  normalised: Float32Array;
  centroid: { x: number; y: number };
  palmNormal: Vec3;
  tipDistances: number[];
  extensionAngles: number[];
}

export interface FeatureVector {
  vector: Float32Array;
  handCount: number;
  /** Highest MediaPipe handedness score across detected hands (0 when none). */
  bestHandScore: number;
  debug: { hands: HandFeatureDebug[]; posePresent: boolean };
}

function writeHandBlock(
  out: Float32Array,
  slotIndex: number,
  hand: HandLandmarks | null,
  shoulderMid: { x: number; y: number } | null,
  shoulderWidth: number,
  posePresent: boolean,
): HandFeatureDebug | null {
  const base = slotIndex * HAND_LANDMARK_COUNT * 3;
  const presenceIndex = 126 + slotIndex;
  const positionIndex = 128 + slotIndex * 2;
  const normalIndex = 132 + slotIndex * 3;
  const tipIndex = 138 + slotIndex * 5;
  const angleIndex = 148 + slotIndex * 5;

  if (!hand) {
    // Absent hand: zeros everywhere plus a 0 presence flag. Left as zeros by default.
    out[presenceIndex] = 0;
    return null;
  }

  const normalised = normaliseHand(hand.landmarks);
  out.set(normalised, base);
  out[presenceIndex] = 1;

  const centroid = handCentroid(hand.landmarks);
  if (posePresent && shoulderMid && shoulderWidth >= EPSILON) {
    out[positionIndex] = (centroid.x - shoulderMid.x) / shoulderWidth;
    out[positionIndex + 1] = (centroid.y - shoulderMid.y) / shoulderWidth;
  }

  const normal = palmNormal(hand.landmarks);
  out[normalIndex] = normal[0];
  out[normalIndex + 1] = normal[1];
  out[normalIndex + 2] = normal[2];

  const tips = fingertipDistances(hand.landmarks);
  for (let i = 0; i < tips.length; i += 1) out[tipIndex + i] = tips[i] as number;

  const angles = extensionAngles(hand.landmarks);
  for (let i = 0; i < angles.length; i += 1) out[angleIndex + i] = angles[i] as number;

  return {
    slot: slotIndex === 0 ? 'left' : 'right',
    normalised,
    centroid,
    palmNormal: normal,
    tipDistances: tips,
    extensionAngles: angles,
  };
}

function resolvePose(pose: PoseLandmarks | null): {
  mid: { x: number; y: number } | null;
  width: number;
} {
  if (!pose) return { mid: null, width: 0 };
  const ls = pose.landmarks[POSE.LEFT_SHOULDER];
  const rs = pose.landmarks[POSE.RIGHT_SHOULDER];
  if (!isUsable(ls) || !isUsable(rs)) return { mid: null, width: 0 };

  const left = ls as Landmark;
  const right = rs as Landmark;
  const mid = { x: (left.x + right.x) / 2, y: (left.y + right.y) / 2 };
  const dx = left.x - right.x;
  const dy = left.y - right.y;
  return { mid, width: Math.sqrt(dx * dx + dy * dy) };
}

/**
 * Convert a frame of landmarks into the fixed-length feature vector the classifier
 * consumes. Always returns exactly `FEATURE_VECTOR_LENGTH` finite floats.
 */
export function extractFeatureVector(frame: FrameLandmarks): FeatureVector {
  const out = new Float32Array(FEATURE_VECTOR_LENGTH);
  const [left, right] = selectHandSlots(frame.hands);
  const { mid, width } = resolvePose(frame.pose);
  const posePresent = mid !== null && width >= EPSILON;

  const debugHands: HandFeatureDebug[] = [];
  const leftDebug = writeHandBlock(out, 0, left, mid, width, posePresent);
  const rightDebug = writeHandBlock(out, 1, right, mid, width, posePresent);
  if (leftDebug) debugHands.push(leftDebug);
  if (rightDebug) debugHands.push(rightDebug);

  out[158] = posePresent ? 1 : 0;

  let handCount = 0;
  let bestHandScore = 0;
  if (left) {
    handCount += 1;
    bestHandScore = Math.max(bestHandScore, left.score);
  }
  if (right) {
    handCount += 1;
    bestHandScore = Math.max(bestHandScore, right.score);
  }

  return {
    vector: out,
    handCount,
    bestHandScore,
    debug: { hands: debugHands, posePresent },
  };
}

/** Human-readable description of the feature layout, used by the data-collection UI. */
export const FEATURE_LAYOUT_DESCRIPTION: ReadonlyArray<{ range: string; description: string }> = [
  { range: '0-125', description: '2 hands x 21 landmarks x (x, y, z), wrist-origin and hand-size scaled' },
  { range: '126-127', description: 'Hand presence flags (left, right)' },
  { range: '128-131', description: 'Hand centroid relative to shoulder midpoint, divided by shoulder width' },
  { range: '132-137', description: 'Palm unit normal per hand (x, y, z)' },
  { range: '138-147', description: 'Wrist to fingertip distances per hand' },
  { range: '148-157', description: 'Finger extension angles in radians per hand' },
  { range: '158', description: 'Pose presence flag' },
];
