/**
 * Feature parity between the browser and the training pipeline — risk R14.
 *
 * `lib/vision/features.ts` and `ml/signdata/features.py` implement the same 159-float
 * feature vector. If they ever disagree, the browser feeds the classifier vectors that mean
 * something different from what it was trained on, and the result is confident nonsense
 * that no other test would catch.
 *
 * The fixtures are generated by `ml/scripts/build_fixtures.py` (`npm run ml:fixtures`) and
 * contain deliberately awkward frames: absent hands, incomplete hands, NaN coordinates,
 * degenerate zero-scale hands, hands 250x larger than the others, duplicate handedness,
 * truncated pose arrays. Both implementations must agree on all of them.
 *
 * If this test fails:
 *   1. Work out which side changed.
 *   2. If the change is intentional, bump FEATURE_VERSION in BOTH `lib/types.ts` and
 *      `ml/signdata/constants.py`, regenerate the fixtures, retrain, and update the model
 *      card. A silent feature change invalidates every model trained before it.
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

import { FEATURE_VECTOR_LENGTH, FEATURE_VERSION, type FrameLandmarks } from '@/lib/types';
import { extractFeatureVector } from '@/lib/vision/features';

interface FixtureLandmark {
  x: number | string;
  y: number | string;
  z: number | string;
  visibility?: number;
}

interface FixtureCase {
  name: string;
  description: string;
  frame: {
    hands: Array<{ handedness: string; score: number; landmarks: FixtureLandmark[] }>;
    pose: { landmarks: FixtureLandmark[] } | null;
    timestampMs: number;
  };
  expectedVector: number[];
  expectedHandCount: number;
  expectedBestHandScore: number;
}

interface FixtureFile {
  featureVersion: string;
  generator: string;
  tolerance: number;
  valueEncoding: string;
  cases: FixtureCase[];
}

const FIXTURE_PATH = resolve(__dirname, 'fixtures', 'features-parity.json');

/**
 * JSON cannot hold NaN or Infinity, so the fixture writes them as strings. Decode them back
 * into real numbers here — the alternative would be to drop the non-finite cases entirely,
 * which are exactly the ones most likely to break in one language and not the other.
 */
function decodeNumber(value: number | string): number {
  if (typeof value === 'number') return value;
  if (value === 'NaN') return Number.NaN;
  if (value === 'Infinity') return Number.POSITIVE_INFINITY;
  if (value === '-Infinity') return Number.NEGATIVE_INFINITY;
  const parsed = Number(value);
  if (Number.isNaN(parsed)) throw new Error(`Fixture contains a non-numeric value: ${value}`);
  return parsed;
}

function decodeFrame(raw: FixtureCase['frame']): FrameLandmarks {
  return {
    hands: raw.hands.map((hand) => ({
      handedness: hand.handedness === 'Left' ? 'Left' : 'Right',
      score: decodeNumber(hand.score),
      landmarks: hand.landmarks.map((landmark) => ({
        x: decodeNumber(landmark.x),
        y: decodeNumber(landmark.y),
        z: decodeNumber(landmark.z),
        ...(landmark.visibility === undefined ? {} : { visibility: landmark.visibility }),
      })),
    })),
    pose: raw.pose
      ? {
          landmarks: raw.pose.landmarks.map((landmark) => ({
            x: decodeNumber(landmark.x),
            y: decodeNumber(landmark.y),
            z: decodeNumber(landmark.z),
            ...(landmark.visibility === undefined ? {} : { visibility: landmark.visibility }),
          })),
        }
      : null,
    timestampMs: raw.timestampMs,
  };
}

const fixture = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8')) as FixtureFile;

describe('feature parity fixtures', () => {
  it('were generated for the feature version this build implements', () => {
    expect(
      fixture.featureVersion,
      `The fixtures were generated for "${fixture.featureVersion}" but this build implements ` +
        `"${FEATURE_VERSION}". Regenerate with: npm run ml:fixtures`,
    ).toBe(FEATURE_VERSION);
  });

  it('cover the awkward cases, not just the happy path', () => {
    const names = fixture.cases.map((entry) => entry.name);
    expect(names).toContain('empty-frame');
    expect(names).toContain('hand-with-nan-coordinates');
    expect(names).toContain('degenerate-hand-zero-scale-guard');
    expect(names).toContain('incomplete-hand-ignored');
    expect(names).toContain('duplicate-handedness-higher-score-wins');
    expect(names.length).toBeGreaterThanOrEqual(15);
  });
});

describe.each(fixture.cases.map((entry) => [entry.name, entry] as const))(
  'parity: %s',
  (name, testCase) => {
    it(`matches the Python implementation (${testCase.description})`, () => {
      const result = extractFeatureVector(decodeFrame(testCase.frame));

      expect(result.vector.length).toBe(FEATURE_VECTOR_LENGTH);

      // Every value must be finite. A NaN that reaches a classifier produces a confident
      // prediction for whatever class happens to win the argmax of NaNs.
      for (let index = 0; index < result.vector.length; index += 1) {
        expect(
          Number.isFinite(result.vector[index] as number),
          `value at index ${index} is ${String(result.vector[index])}`,
        ).toBe(true);
      }

      let worstIndex = -1;
      let worstDifference = 0;
      for (let index = 0; index < result.vector.length; index += 1) {
        const difference = Math.abs((result.vector[index] as number) - (testCase.expectedVector[index] as number));
        if (difference > worstDifference) {
          worstDifference = difference;
          worstIndex = index;
        }
      }

      expect(
        worstDifference,
        `case "${name}" differs from Python at index ${worstIndex}: ` +
          `TypeScript=${String(result.vector[worstIndex])}, ` +
          `Python=${String(testCase.expectedVector[worstIndex])}, ` +
          `difference=${worstDifference}. ` +
          'If the change was intentional, bump FEATURE_VERSION in lib/types.ts AND ' +
          'ml/signdata/constants.py, then regenerate the fixtures.',
      ).toBeLessThanOrEqual(fixture.tolerance);

      expect(result.handCount).toBe(testCase.expectedHandCount);
      expect(result.bestHandScore).toBeCloseTo(testCase.expectedBestHandScore, 6);
    });
  },
);
